// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: pkg/common/protocol/proto/agent.proto

package gen

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// InstanceRegistration represents the registration of an instance with the agent
type InstanceRegistration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	InstanceType  string                 `protobuf:"bytes,2,opt,name=instance_type,json=instanceType,proto3" json:"instance_type,omitempty"`
	Region        string                 `protobuf:"bytes,3,opt,name=region,proto3" json:"region,omitempty"`
	Zone          string                 `protobuf:"bytes,4,opt,name=zone,proto3" json:"zone,omitempty"`
	Provider      string                 `protobuf:"bytes,5,opt,name=provider,proto3" json:"provider,omitempty"`
	Thresholds    map[string]float64     `protobuf:"bytes,6,rep,name=thresholds,proto3" json:"thresholds,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	NapTime       int64                  `protobuf:"varint,7,opt,name=nap_time,json=napTime,proto3" json:"nap_time,omitempty"` // in seconds
	Metadata      map[string]string      `protobuf:"bytes,8,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstanceRegistration) Reset() {
	*x = InstanceRegistration{}
	mi := &file_pkg_common_protocol_proto_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstanceRegistration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstanceRegistration) ProtoMessage() {}

func (x *InstanceRegistration) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_common_protocol_proto_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstanceRegistration.ProtoReflect.Descriptor instead.
func (*InstanceRegistration) Descriptor() ([]byte, []int) {
	return file_pkg_common_protocol_proto_agent_proto_rawDescGZIP(), []int{0}
}

func (x *InstanceRegistration) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *InstanceRegistration) GetInstanceType() string {
	if x != nil {
		return x.InstanceType
	}
	return ""
}

func (x *InstanceRegistration) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *InstanceRegistration) GetZone() string {
	if x != nil {
		return x.Zone
	}
	return ""
}

func (x *InstanceRegistration) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *InstanceRegistration) GetThresholds() map[string]float64 {
	if x != nil {
		return x.Thresholds
	}
	return nil
}

func (x *InstanceRegistration) GetNapTime() int64 {
	if x != nil {
		return x.NapTime
	}
	return 0
}

func (x *InstanceRegistration) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// RegistrationResponse is the response to an instance registration
type RegistrationResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Success           bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error             string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	AgentId           string                 `protobuf:"bytes,3,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	HeartbeatInterval int64                  `protobuf:"varint,4,opt,name=heartbeat_interval,json=heartbeatInterval,proto3" json:"heartbeat_interval,omitempty"` // in seconds
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RegistrationResponse) Reset() {
	*x = RegistrationResponse{}
	mi := &file_pkg_common_protocol_proto_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistrationResponse) ProtoMessage() {}

func (x *RegistrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_common_protocol_proto_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistrationResponse.ProtoReflect.Descriptor instead.
func (*RegistrationResponse) Descriptor() ([]byte, []int) {
	return file_pkg_common_protocol_proto_agent_proto_rawDescGZIP(), []int{1}
}

func (x *RegistrationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegistrationResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *RegistrationResponse) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *RegistrationResponse) GetHeartbeatInterval() int64 {
	if x != nil {
		return x.HeartbeatInterval
	}
	return 0
}

// UnregisterRequest is the request to unregister an instance
type UnregisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnregisterRequest) Reset() {
	*x = UnregisterRequest{}
	mi := &file_pkg_common_protocol_proto_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterRequest) ProtoMessage() {}

func (x *UnregisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_common_protocol_proto_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterRequest.ProtoReflect.Descriptor instead.
func (*UnregisterRequest) Descriptor() ([]byte, []int) {
	return file_pkg_common_protocol_proto_agent_proto_rawDescGZIP(), []int{2}
}

func (x *UnregisterRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

// UnregisterResponse is the response to an instance unregistration
type UnregisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnregisterResponse) Reset() {
	*x = UnregisterResponse{}
	mi := &file_pkg_common_protocol_proto_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterResponse) ProtoMessage() {}

func (x *UnregisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_common_protocol_proto_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterResponse.ProtoReflect.Descriptor instead.
func (*UnregisterResponse) Descriptor() ([]byte, []int) {
	return file_pkg_common_protocol_proto_agent_proto_rawDescGZIP(), []int{3}
}

func (x *UnregisterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UnregisterResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// IdleNotificationRequest is the request to send an idle notification
type IdleNotificationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	IdleSince     int64                  `protobuf:"varint,2,opt,name=idle_since,json=idleSince,proto3" json:"idle_since,omitempty"`          // unix timestamp
	IdleDuration  int64                  `protobuf:"varint,3,opt,name=idle_duration,json=idleDuration,proto3" json:"idle_duration,omitempty"` // in seconds
	ResourceUsage map[string]float64     `protobuf:"bytes,4,rep,name=resource_usage,json=resourceUsage,proto3" json:"resource_usage,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdleNotificationRequest) Reset() {
	*x = IdleNotificationRequest{}
	mi := &file_pkg_common_protocol_proto_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdleNotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdleNotificationRequest) ProtoMessage() {}

func (x *IdleNotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_common_protocol_proto_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdleNotificationRequest.ProtoReflect.Descriptor instead.
func (*IdleNotificationRequest) Descriptor() ([]byte, []int) {
	return file_pkg_common_protocol_proto_agent_proto_rawDescGZIP(), []int{4}
}

func (x *IdleNotificationRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *IdleNotificationRequest) GetIdleSince() int64 {
	if x != nil {
		return x.IdleSince
	}
	return 0
}

func (x *IdleNotificationRequest) GetIdleDuration() int64 {
	if x != nil {
		return x.IdleDuration
	}
	return 0
}

func (x *IdleNotificationRequest) GetResourceUsage() map[string]float64 {
	if x != nil {
		return x.ResourceUsage
	}
	return nil
}

// IdleNotificationResponse is the response to an idle notification
type IdleNotificationResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Action          string                 `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"` // "none", "wait", "stop"
	Reason          string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	ScheduledAction *ScheduledAction       `protobuf:"bytes,3,opt,name=scheduled_action,json=scheduledAction,proto3" json:"scheduled_action,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *IdleNotificationResponse) Reset() {
	*x = IdleNotificationResponse{}
	mi := &file_pkg_common_protocol_proto_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdleNotificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdleNotificationResponse) ProtoMessage() {}

func (x *IdleNotificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_common_protocol_proto_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdleNotificationResponse.ProtoReflect.Descriptor instead.
func (*IdleNotificationResponse) Descriptor() ([]byte, []int) {
	return file_pkg_common_protocol_proto_agent_proto_rawDescGZIP(), []int{5}
}

func (x *IdleNotificationResponse) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *IdleNotificationResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *IdleNotificationResponse) GetScheduledAction() *ScheduledAction {
	if x != nil {
		return x.ScheduledAction
	}
	return nil
}

// ScheduledAction represents an action scheduled for an instance
type ScheduledAction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        string                 `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`                                     // "stop", "start"
	ScheduledTime int64                  `protobuf:"varint,2,opt,name=scheduled_time,json=scheduledTime,proto3" json:"scheduled_time,omitempty"` // unix timestamp
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScheduledAction) Reset() {
	*x = ScheduledAction{}
	mi := &file_pkg_common_protocol_proto_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduledAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduledAction) ProtoMessage() {}

func (x *ScheduledAction) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_common_protocol_proto_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduledAction.ProtoReflect.Descriptor instead.
func (*ScheduledAction) Descriptor() ([]byte, []int) {
	return file_pkg_common_protocol_proto_agent_proto_rawDescGZIP(), []int{6}
}

func (x *ScheduledAction) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *ScheduledAction) GetScheduledTime() int64 {
	if x != nil {
		return x.ScheduledTime
	}
	return 0
}

func (x *ScheduledAction) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// HeartbeatRequest is the request to send a heartbeat
type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // unix timestamp
	State         string                 `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	ResourceUsage map[string]float64     `protobuf:"bytes,4,rep,name=resource_usage,json=resourceUsage,proto3" json:"resource_usage,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_pkg_common_protocol_proto_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_common_protocol_proto_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_pkg_common_protocol_proto_agent_proto_rawDescGZIP(), []int{7}
}

func (x *HeartbeatRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *HeartbeatRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *HeartbeatRequest) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *HeartbeatRequest) GetResourceUsage() map[string]float64 {
	if x != nil {
		return x.ResourceUsage
	}
	return nil
}

// HeartbeatResponse is the response to a heartbeat
type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Acknowledged  bool                   `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	Commands      []*Command             `protobuf:"bytes,2,rep,name=commands,proto3" json:"commands,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_pkg_common_protocol_proto_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_common_protocol_proto_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_pkg_common_protocol_proto_agent_proto_rawDescGZIP(), []int{8}
}

func (x *HeartbeatResponse) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

func (x *HeartbeatResponse) GetCommands() []*Command {
	if x != nil {
		return x.Commands
	}
	return nil
}

// Command represents a command for an instance to execute
type Command struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       string                 `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"` // "ping", "stop", "start"
	Parameters    map[string]string      `protobuf:"bytes,2,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_pkg_common_protocol_proto_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_common_protocol_proto_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_pkg_common_protocol_proto_agent_proto_rawDescGZIP(), []int{9}
}

func (x *Command) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *Command) GetParameters() map[string]string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

// StateChangeRequest is the request to report a state change
type StateChangeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	PreviousState string                 `protobuf:"bytes,2,opt,name=previous_state,json=previousState,proto3" json:"previous_state,omitempty"`
	CurrentState  string                 `protobuf:"bytes,3,opt,name=current_state,json=currentState,proto3" json:"current_state,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // unix timestamp
	Reason        string                 `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StateChangeRequest) Reset() {
	*x = StateChangeRequest{}
	mi := &file_pkg_common_protocol_proto_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateChangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateChangeRequest) ProtoMessage() {}

func (x *StateChangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_common_protocol_proto_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateChangeRequest.ProtoReflect.Descriptor instead.
func (*StateChangeRequest) Descriptor() ([]byte, []int) {
	return file_pkg_common_protocol_proto_agent_proto_rawDescGZIP(), []int{10}
}

func (x *StateChangeRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *StateChangeRequest) GetPreviousState() string {
	if x != nil {
		return x.PreviousState
	}
	return ""
}

func (x *StateChangeRequest) GetCurrentState() string {
	if x != nil {
		return x.CurrentState
	}
	return ""
}

func (x *StateChangeRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *StateChangeRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// StateChangeResponse is the response to a state change report
type StateChangeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Acknowledged  bool                   `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StateChangeResponse) Reset() {
	*x = StateChangeResponse{}
	mi := &file_pkg_common_protocol_proto_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateChangeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateChangeResponse) ProtoMessage() {}

func (x *StateChangeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_common_protocol_proto_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateChangeResponse.ProtoReflect.Descriptor instead.
func (*StateChangeResponse) Descriptor() ([]byte, []int) {
	return file_pkg_common_protocol_proto_agent_proto_rawDescGZIP(), []int{11}
}

func (x *StateChangeResponse) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

func (x *StateChangeResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// GetInstanceInfoRequest is the request to get instance information
type GetInstanceInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInstanceInfoRequest) Reset() {
	*x = GetInstanceInfoRequest{}
	mi := &file_pkg_common_protocol_proto_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInstanceInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInstanceInfoRequest) ProtoMessage() {}

func (x *GetInstanceInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_common_protocol_proto_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInstanceInfoRequest.ProtoReflect.Descriptor instead.
func (*GetInstanceInfoRequest) Descriptor() ([]byte, []int) {
	return file_pkg_common_protocol_proto_agent_proto_rawDescGZIP(), []int{12}
}

func (x *GetInstanceInfoRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

// GetInstanceInfoResponse is the response with instance information
type GetInstanceInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Region        string                 `protobuf:"bytes,4,opt,name=region,proto3" json:"region,omitempty"`
	Zone          string                 `protobuf:"bytes,5,opt,name=zone,proto3" json:"zone,omitempty"`
	State         string                 `protobuf:"bytes,6,opt,name=state,proto3" json:"state,omitempty"`
	LaunchTime    *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=launch_time,json=launchTime,proto3" json:"launch_time,omitempty"`
	Provider      string                 `protobuf:"bytes,8,opt,name=provider,proto3" json:"provider,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInstanceInfoResponse) Reset() {
	*x = GetInstanceInfoResponse{}
	mi := &file_pkg_common_protocol_proto_agent_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInstanceInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInstanceInfoResponse) ProtoMessage() {}

func (x *GetInstanceInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_common_protocol_proto_agent_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInstanceInfoResponse.ProtoReflect.Descriptor instead.
func (*GetInstanceInfoResponse) Descriptor() ([]byte, []int) {
	return file_pkg_common_protocol_proto_agent_proto_rawDescGZIP(), []int{13}
}

func (x *GetInstanceInfoResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetInstanceInfoResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetInstanceInfoResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *GetInstanceInfoResponse) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *GetInstanceInfoResponse) GetZone() string {
	if x != nil {
		return x.Zone
	}
	return ""
}

func (x *GetInstanceInfoResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *GetInstanceInfoResponse) GetLaunchTime() *timestamppb.Timestamp {
	if x != nil {
		return x.LaunchTime
	}
	return nil
}

func (x *GetInstanceInfoResponse) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

// StopInstanceRequest is the request to stop an instance
type StopInstanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopInstanceRequest) Reset() {
	*x = StopInstanceRequest{}
	mi := &file_pkg_common_protocol_proto_agent_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopInstanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopInstanceRequest) ProtoMessage() {}

func (x *StopInstanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_common_protocol_proto_agent_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopInstanceRequest.ProtoReflect.Descriptor instead.
func (*StopInstanceRequest) Descriptor() ([]byte, []int) {
	return file_pkg_common_protocol_proto_agent_proto_rawDescGZIP(), []int{14}
}

func (x *StopInstanceRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

// StopInstanceResponse is the response to a stop instance request
type StopInstanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopInstanceResponse) Reset() {
	*x = StopInstanceResponse{}
	mi := &file_pkg_common_protocol_proto_agent_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopInstanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopInstanceResponse) ProtoMessage() {}

func (x *StopInstanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_common_protocol_proto_agent_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopInstanceResponse.ProtoReflect.Descriptor instead.
func (*StopInstanceResponse) Descriptor() ([]byte, []int) {
	return file_pkg_common_protocol_proto_agent_proto_rawDescGZIP(), []int{15}
}

func (x *StopInstanceResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StopInstanceResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// StartInstanceRequest is the request to start an instance
type StartInstanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartInstanceRequest) Reset() {
	*x = StartInstanceRequest{}
	mi := &file_pkg_common_protocol_proto_agent_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartInstanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartInstanceRequest) ProtoMessage() {}

func (x *StartInstanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_common_protocol_proto_agent_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartInstanceRequest.ProtoReflect.Descriptor instead.
func (*StartInstanceRequest) Descriptor() ([]byte, []int) {
	return file_pkg_common_protocol_proto_agent_proto_rawDescGZIP(), []int{16}
}

func (x *StartInstanceRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

// StartInstanceResponse is the response to a start instance request
type StartInstanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartInstanceResponse) Reset() {
	*x = StartInstanceResponse{}
	mi := &file_pkg_common_protocol_proto_agent_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartInstanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartInstanceResponse) ProtoMessage() {}

func (x *StartInstanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_common_protocol_proto_agent_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartInstanceResponse.ProtoReflect.Descriptor instead.
func (*StartInstanceResponse) Descriptor() ([]byte, []int) {
	return file_pkg_common_protocol_proto_agent_proto_rawDescGZIP(), []int{17}
}

func (x *StartInstanceResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StartInstanceResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// CloudActionRequest is the request to perform a cloud action
type CloudActionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Action        string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	Parameters    map[string]string      `protobuf:"bytes,3,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloudActionRequest) Reset() {
	*x = CloudActionRequest{}
	mi := &file_pkg_common_protocol_proto_agent_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloudActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloudActionRequest) ProtoMessage() {}

func (x *CloudActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_common_protocol_proto_agent_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloudActionRequest.ProtoReflect.Descriptor instead.
func (*CloudActionRequest) Descriptor() ([]byte, []int) {
	return file_pkg_common_protocol_proto_agent_proto_rawDescGZIP(), []int{18}
}

func (x *CloudActionRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *CloudActionRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *CloudActionRequest) GetParameters() map[string]string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

// CloudActionResponse is the response to a cloud action request
type CloudActionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloudActionResponse) Reset() {
	*x = CloudActionResponse{}
	mi := &file_pkg_common_protocol_proto_agent_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloudActionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloudActionResponse) ProtoMessage() {}

func (x *CloudActionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_common_protocol_proto_agent_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloudActionResponse.ProtoReflect.Descriptor instead.
func (*CloudActionResponse) Descriptor() ([]byte, []int) {
	return file_pkg_common_protocol_proto_agent_proto_rawDescGZIP(), []int{19}
}

func (x *CloudActionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CloudActionResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// ListCloudProvidersRequest is the request to list cloud providers
type ListCloudProvidersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCloudProvidersRequest) Reset() {
	*x = ListCloudProvidersRequest{}
	mi := &file_pkg_common_protocol_proto_agent_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCloudProvidersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCloudProvidersRequest) ProtoMessage() {}

func (x *ListCloudProvidersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_common_protocol_proto_agent_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCloudProvidersRequest.ProtoReflect.Descriptor instead.
func (*ListCloudProvidersRequest) Descriptor() ([]byte, []int) {
	return file_pkg_common_protocol_proto_agent_proto_rawDescGZIP(), []int{20}
}

// CloudProviderInfo contains information about a cloud provider
type CloudProviderInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Plugin        string                 `protobuf:"bytes,3,opt,name=plugin,proto3" json:"plugin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloudProviderInfo) Reset() {
	*x = CloudProviderInfo{}
	mi := &file_pkg_common_protocol_proto_agent_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloudProviderInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloudProviderInfo) ProtoMessage() {}

func (x *CloudProviderInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_common_protocol_proto_agent_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloudProviderInfo.ProtoReflect.Descriptor instead.
func (*CloudProviderInfo) Descriptor() ([]byte, []int) {
	return file_pkg_common_protocol_proto_agent_proto_rawDescGZIP(), []int{21}
}

func (x *CloudProviderInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CloudProviderInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *CloudProviderInfo) GetPlugin() string {
	if x != nil {
		return x.Plugin
	}
	return ""
}

// ListCloudProvidersResponse is the response with cloud provider information
type ListCloudProvidersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Providers     []*CloudProviderInfo   `protobuf:"bytes,1,rep,name=providers,proto3" json:"providers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCloudProvidersResponse) Reset() {
	*x = ListCloudProvidersResponse{}
	mi := &file_pkg_common_protocol_proto_agent_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCloudProvidersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCloudProvidersResponse) ProtoMessage() {}

func (x *ListCloudProvidersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_common_protocol_proto_agent_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCloudProvidersResponse.ProtoReflect.Descriptor instead.
func (*ListCloudProvidersResponse) Descriptor() ([]byte, []int) {
	return file_pkg_common_protocol_proto_agent_proto_rawDescGZIP(), []int{22}
}

func (x *ListCloudProvidersResponse) GetProviders() []*CloudProviderInfo {
	if x != nil {
		return x.Providers
	}
	return nil
}

var File_pkg_common_protocol_proto_agent_proto protoreflect.FileDescriptor

const file_pkg_common_protocol_proto_agent_proto_rawDesc = "" +
	"\n" +
	"%pkg/common/protocol/proto/agent.proto\x12\bprotocol\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd5\x03\n" +
	"\x14InstanceRegistration\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12#\n" +
	"\rinstance_type\x18\x02 \x01(\tR\finstanceType\x12\x16\n" +
	"\x06region\x18\x03 \x01(\tR\x06region\x12\x12\n" +
	"\x04zone\x18\x04 \x01(\tR\x04zone\x12\x1a\n" +
	"\bprovider\x18\x05 \x01(\tR\bprovider\x12N\n" +
	"\n" +
	"thresholds\x18\x06 \x03(\v2..protocol.InstanceRegistration.ThresholdsEntryR\n" +
	"thresholds\x12\x19\n" +
	"\bnap_time\x18\a \x01(\x03R\anapTime\x12H\n" +
	"\bmetadata\x18\b \x03(\v2,.protocol.InstanceRegistration.MetadataEntryR\bmetadata\x1a=\n" +
	"\x0fThresholdsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x90\x01\n" +
	"\x14RegistrationResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x19\n" +
	"\bagent_id\x18\x03 \x01(\tR\aagentId\x12-\n" +
	"\x12heartbeat_interval\x18\x04 \x01(\x03R\x11heartbeatInterval\"4\n" +
	"\x11UnregisterRequest\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\"D\n" +
	"\x12UnregisterResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\x9d\x02\n" +
	"\x17IdleNotificationRequest\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12\x1d\n" +
	"\n" +
	"idle_since\x18\x02 \x01(\x03R\tidleSince\x12#\n" +
	"\ridle_duration\x18\x03 \x01(\x03R\fidleDuration\x12[\n" +
	"\x0eresource_usage\x18\x04 \x03(\v24.protocol.IdleNotificationRequest.ResourceUsageEntryR\rresourceUsage\x1a@\n" +
	"\x12ResourceUsageEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\"\x90\x01\n" +
	"\x18IdleNotificationResponse\x12\x16\n" +
	"\x06action\x18\x01 \x01(\tR\x06action\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12D\n" +
	"\x10scheduled_action\x18\x03 \x01(\v2\x19.protocol.ScheduledActionR\x0fscheduledAction\"h\n" +
	"\x0fScheduledAction\x12\x16\n" +
	"\x06action\x18\x01 \x01(\tR\x06action\x12%\n" +
	"\x0escheduled_time\x18\x02 \x01(\x03R\rscheduledTime\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"\xff\x01\n" +
	"\x10HeartbeatRequest\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12\x14\n" +
	"\x05state\x18\x03 \x01(\tR\x05state\x12T\n" +
	"\x0eresource_usage\x18\x04 \x03(\v2-.protocol.HeartbeatRequest.ResourceUsageEntryR\rresourceUsage\x1a@\n" +
	"\x12ResourceUsageEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\"f\n" +
	"\x11HeartbeatResponse\x12\"\n" +
	"\facknowledged\x18\x01 \x01(\bR\facknowledged\x12-\n" +
	"\bcommands\x18\x02 \x03(\v2\x11.protocol.CommandR\bcommands\"\xa5\x01\n" +
	"\aCommand\x12\x18\n" +
	"\acommand\x18\x01 \x01(\tR\acommand\x12A\n" +
	"\n" +
	"parameters\x18\x02 \x03(\v2!.protocol.Command.ParametersEntryR\n" +
	"parameters\x1a=\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb7\x01\n" +
	"\x12StateChangeRequest\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12%\n" +
	"\x0eprevious_state\x18\x02 \x01(\tR\rpreviousState\x12#\n" +
	"\rcurrent_state\x18\x03 \x01(\tR\fcurrentState\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\x12\x16\n" +
	"\x06reason\x18\x05 \x01(\tR\x06reason\"O\n" +
	"\x13StateChangeResponse\x12\"\n" +
	"\facknowledged\x18\x01 \x01(\bR\facknowledged\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"9\n" +
	"\x16GetInstanceInfoRequest\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\"\xec\x01\n" +
	"\x17GetInstanceInfoResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x16\n" +
	"\x06region\x18\x04 \x01(\tR\x06region\x12\x12\n" +
	"\x04zone\x18\x05 \x01(\tR\x04zone\x12\x14\n" +
	"\x05state\x18\x06 \x01(\tR\x05state\x12;\n" +
	"\vlaunch_time\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"launchTime\x12\x1a\n" +
	"\bprovider\x18\b \x01(\tR\bprovider\"6\n" +
	"\x13StopInstanceRequest\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\"F\n" +
	"\x14StopInstanceResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"7\n" +
	"\x14StartInstanceRequest\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\"G\n" +
	"\x15StartInstanceResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\xda\x01\n" +
	"\x12CloudActionRequest\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\x12L\n" +
	"\n" +
	"parameters\x18\x03 \x03(\v2,.protocol.CloudActionRequest.ParametersEntryR\n" +
	"parameters\x1a=\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"E\n" +
	"\x13CloudActionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\x1b\n" +
	"\x19ListCloudProvidersRequest\"Y\n" +
	"\x11CloudProviderInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x16\n" +
	"\x06plugin\x18\x03 \x01(\tR\x06plugin\"W\n" +
	"\x1aListCloudProvidersResponse\x129\n" +
	"\tproviders\x18\x01 \x03(\v2\x1b.protocol.CloudProviderInfoR\tproviders2\xda\x06\n" +
	"\vSnoozeAgent\x12R\n" +
	"\x10RegisterInstance\x12\x1e.protocol.InstanceRegistration\x1a\x1e.protocol.RegistrationResponse\x12O\n" +
	"\x12UnregisterInstance\x12\x1b.protocol.UnregisterRequest\x1a\x1c.protocol.UnregisterResponse\x12]\n" +
	"\x14SendIdleNotification\x12!.protocol.IdleNotificationRequest\x1a\".protocol.IdleNotificationResponse\x12H\n" +
	"\rSendHeartbeat\x12\x1a.protocol.HeartbeatRequest\x1a\x1b.protocol.HeartbeatResponse\x12P\n" +
	"\x11ReportStateChange\x12\x1c.protocol.StateChangeRequest\x1a\x1d.protocol.StateChangeResponse\x12V\n" +
	"\x0fGetInstanceInfo\x12 .protocol.GetInstanceInfoRequest\x1a!.protocol.GetInstanceInfoResponse\x12M\n" +
	"\fStopInstance\x12\x1d.protocol.StopInstanceRequest\x1a\x1e.protocol.StopInstanceResponse\x12P\n" +
	"\rStartInstance\x12\x1e.protocol.StartInstanceRequest\x1a\x1f.protocol.StartInstanceResponse\x12Q\n" +
	"\x12PerformCloudAction\x12\x1c.protocol.CloudActionRequest\x1a\x1d.protocol.CloudActionResponse\x12_\n" +
	"\x12ListCloudProviders\x12#.protocol.ListCloudProvidersRequest\x1a$.protocol.ListCloudProvidersResponseB8Z6github.com/scttfrdmn/snoozebot/pkg/common/protocol/genb\x06proto3"

var (
	file_pkg_common_protocol_proto_agent_proto_rawDescOnce sync.Once
	file_pkg_common_protocol_proto_agent_proto_rawDescData []byte
)

func file_pkg_common_protocol_proto_agent_proto_rawDescGZIP() []byte {
	file_pkg_common_protocol_proto_agent_proto_rawDescOnce.Do(func() {
		file_pkg_common_protocol_proto_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_common_protocol_proto_agent_proto_rawDesc), len(file_pkg_common_protocol_proto_agent_proto_rawDesc)))
	})
	return file_pkg_common_protocol_proto_agent_proto_rawDescData
}

var file_pkg_common_protocol_proto_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_pkg_common_protocol_proto_agent_proto_goTypes = []any{
	(*InstanceRegistration)(nil),       // 0: protocol.InstanceRegistration
	(*RegistrationResponse)(nil),       // 1: protocol.RegistrationResponse
	(*UnregisterRequest)(nil),          // 2: protocol.UnregisterRequest
	(*UnregisterResponse)(nil),         // 3: protocol.UnregisterResponse
	(*IdleNotificationRequest)(nil),    // 4: protocol.IdleNotificationRequest
	(*IdleNotificationResponse)(nil),   // 5: protocol.IdleNotificationResponse
	(*ScheduledAction)(nil),            // 6: protocol.ScheduledAction
	(*HeartbeatRequest)(nil),           // 7: protocol.HeartbeatRequest
	(*HeartbeatResponse)(nil),          // 8: protocol.HeartbeatResponse
	(*Command)(nil),                    // 9: protocol.Command
	(*StateChangeRequest)(nil),         // 10: protocol.StateChangeRequest
	(*StateChangeResponse)(nil),        // 11: protocol.StateChangeResponse
	(*GetInstanceInfoRequest)(nil),     // 12: protocol.GetInstanceInfoRequest
	(*GetInstanceInfoResponse)(nil),    // 13: protocol.GetInstanceInfoResponse
	(*StopInstanceRequest)(nil),        // 14: protocol.StopInstanceRequest
	(*StopInstanceResponse)(nil),       // 15: protocol.StopInstanceResponse
	(*StartInstanceRequest)(nil),       // 16: protocol.StartInstanceRequest
	(*StartInstanceResponse)(nil),      // 17: protocol.StartInstanceResponse
	(*CloudActionRequest)(nil),         // 18: protocol.CloudActionRequest
	(*CloudActionResponse)(nil),        // 19: protocol.CloudActionResponse
	(*ListCloudProvidersRequest)(nil),  // 20: protocol.ListCloudProvidersRequest
	(*CloudProviderInfo)(nil),          // 21: protocol.CloudProviderInfo
	(*ListCloudProvidersResponse)(nil), // 22: protocol.ListCloudProvidersResponse
	nil,                                // 23: protocol.InstanceRegistration.ThresholdsEntry
	nil,                                // 24: protocol.InstanceRegistration.MetadataEntry
	nil,                                // 25: protocol.IdleNotificationRequest.ResourceUsageEntry
	nil,                                // 26: protocol.HeartbeatRequest.ResourceUsageEntry
	nil,                                // 27: protocol.Command.ParametersEntry
	nil,                                // 28: protocol.CloudActionRequest.ParametersEntry
	(*timestamppb.Timestamp)(nil),      // 29: google.protobuf.Timestamp
}
var file_pkg_common_protocol_proto_agent_proto_depIdxs = []int32{
	23, // 0: protocol.InstanceRegistration.thresholds:type_name -> protocol.InstanceRegistration.ThresholdsEntry
	24, // 1: protocol.InstanceRegistration.metadata:type_name -> protocol.InstanceRegistration.MetadataEntry
	25, // 2: protocol.IdleNotificationRequest.resource_usage:type_name -> protocol.IdleNotificationRequest.ResourceUsageEntry
	6,  // 3: protocol.IdleNotificationResponse.scheduled_action:type_name -> protocol.ScheduledAction
	26, // 4: protocol.HeartbeatRequest.resource_usage:type_name -> protocol.HeartbeatRequest.ResourceUsageEntry
	9,  // 5: protocol.HeartbeatResponse.commands:type_name -> protocol.Command
	27, // 6: protocol.Command.parameters:type_name -> protocol.Command.ParametersEntry
	29, // 7: protocol.GetInstanceInfoResponse.launch_time:type_name -> google.protobuf.Timestamp
	28, // 8: protocol.CloudActionRequest.parameters:type_name -> protocol.CloudActionRequest.ParametersEntry
	21, // 9: protocol.ListCloudProvidersResponse.providers:type_name -> protocol.CloudProviderInfo
	0,  // 10: protocol.SnoozeAgent.RegisterInstance:input_type -> protocol.InstanceRegistration
	2,  // 11: protocol.SnoozeAgent.UnregisterInstance:input_type -> protocol.UnregisterRequest
	4,  // 12: protocol.SnoozeAgent.SendIdleNotification:input_type -> protocol.IdleNotificationRequest
	7,  // 13: protocol.SnoozeAgent.SendHeartbeat:input_type -> protocol.HeartbeatRequest
	10, // 14: protocol.SnoozeAgent.ReportStateChange:input_type -> protocol.StateChangeRequest
	12, // 15: protocol.SnoozeAgent.GetInstanceInfo:input_type -> protocol.GetInstanceInfoRequest
	14, // 16: protocol.SnoozeAgent.StopInstance:input_type -> protocol.StopInstanceRequest
	16, // 17: protocol.SnoozeAgent.StartInstance:input_type -> protocol.StartInstanceRequest
	18, // 18: protocol.SnoozeAgent.PerformCloudAction:input_type -> protocol.CloudActionRequest
	20, // 19: protocol.SnoozeAgent.ListCloudProviders:input_type -> protocol.ListCloudProvidersRequest
	1,  // 20: protocol.SnoozeAgent.RegisterInstance:output_type -> protocol.RegistrationResponse
	3,  // 21: protocol.SnoozeAgent.UnregisterInstance:output_type -> protocol.UnregisterResponse
	5,  // 22: protocol.SnoozeAgent.SendIdleNotification:output_type -> protocol.IdleNotificationResponse
	8,  // 23: protocol.SnoozeAgent.SendHeartbeat:output_type -> protocol.HeartbeatResponse
	11, // 24: protocol.SnoozeAgent.ReportStateChange:output_type -> protocol.StateChangeResponse
	13, // 25: protocol.SnoozeAgent.GetInstanceInfo:output_type -> protocol.GetInstanceInfoResponse
	15, // 26: protocol.SnoozeAgent.StopInstance:output_type -> protocol.StopInstanceResponse
	17, // 27: protocol.SnoozeAgent.StartInstance:output_type -> protocol.StartInstanceResponse
	19, // 28: protocol.SnoozeAgent.PerformCloudAction:output_type -> protocol.CloudActionResponse
	22, // 29: protocol.SnoozeAgent.ListCloudProviders:output_type -> protocol.ListCloudProvidersResponse
	20, // [20:30] is the sub-list for method output_type
	10, // [10:20] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_pkg_common_protocol_proto_agent_proto_init() }
func file_pkg_common_protocol_proto_agent_proto_init() {
	if File_pkg_common_protocol_proto_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_common_protocol_proto_agent_proto_rawDesc), len(file_pkg_common_protocol_proto_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_common_protocol_proto_agent_proto_goTypes,
		DependencyIndexes: file_pkg_common_protocol_proto_agent_proto_depIdxs,
		MessageInfos:      file_pkg_common_protocol_proto_agent_proto_msgTypes,
	}.Build()
	File_pkg_common_protocol_proto_agent_proto = out.File
	file_pkg_common_protocol_proto_agent_proto_goTypes = nil
	file_pkg_common_protocol_proto_agent_proto_depIdxs = nil
}
