linters:
  enable:
    - gosec
    - gofmt
    - govet
    - staticcheck
    - gosimple
    - ineffassign
    - unused
    - errcheck
    - misspell
    - revive

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - errcheck

run:
  timeout: 5m

linters-settings:
  gosec:
    excludes:
      - G101  # Look for hard coded credentials - too many false positives
      - G307  # Deferring a method which returns an error - often false positive
  
  errcheck:
    check-type-assertions: true

  revive:
    rules:
      - name: exported
        severity: warning
        disabled: false