// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: cloud_provider.proto

package plugin

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetInstanceInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInstanceInfoRequest) Reset() {
	*x = GetInstanceInfoRequest{}
	mi := &file_cloud_provider_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInstanceInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInstanceInfoRequest) ProtoMessage() {}

func (x *GetInstanceInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_provider_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInstanceInfoRequest.ProtoReflect.Descriptor instead.
func (*GetInstanceInfoRequest) Descriptor() ([]byte, []int) {
	return file_cloud_provider_proto_rawDescGZIP(), []int{0}
}

type GetInstanceInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Region        string                 `protobuf:"bytes,4,opt,name=region,proto3" json:"region,omitempty"`
	Zone          string                 `protobuf:"bytes,5,opt,name=zone,proto3" json:"zone,omitempty"`
	State         string                 `protobuf:"bytes,6,opt,name=state,proto3" json:"state,omitempty"`
	LaunchTime    *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=launch_time,json=launchTime,proto3" json:"launch_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInstanceInfoResponse) Reset() {
	*x = GetInstanceInfoResponse{}
	mi := &file_cloud_provider_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInstanceInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInstanceInfoResponse) ProtoMessage() {}

func (x *GetInstanceInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_provider_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInstanceInfoResponse.ProtoReflect.Descriptor instead.
func (*GetInstanceInfoResponse) Descriptor() ([]byte, []int) {
	return file_cloud_provider_proto_rawDescGZIP(), []int{1}
}

func (x *GetInstanceInfoResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetInstanceInfoResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetInstanceInfoResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *GetInstanceInfoResponse) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *GetInstanceInfoResponse) GetZone() string {
	if x != nil {
		return x.Zone
	}
	return ""
}

func (x *GetInstanceInfoResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *GetInstanceInfoResponse) GetLaunchTime() *timestamppb.Timestamp {
	if x != nil {
		return x.LaunchTime
	}
	return nil
}

type StopInstanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopInstanceRequest) Reset() {
	*x = StopInstanceRequest{}
	mi := &file_cloud_provider_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopInstanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopInstanceRequest) ProtoMessage() {}

func (x *StopInstanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_provider_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopInstanceRequest.ProtoReflect.Descriptor instead.
func (*StopInstanceRequest) Descriptor() ([]byte, []int) {
	return file_cloud_provider_proto_rawDescGZIP(), []int{2}
}

type StopInstanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopInstanceResponse) Reset() {
	*x = StopInstanceResponse{}
	mi := &file_cloud_provider_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopInstanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopInstanceResponse) ProtoMessage() {}

func (x *StopInstanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_provider_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopInstanceResponse.ProtoReflect.Descriptor instead.
func (*StopInstanceResponse) Descriptor() ([]byte, []int) {
	return file_cloud_provider_proto_rawDescGZIP(), []int{3}
}

func (x *StopInstanceResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StopInstanceResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type StartInstanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartInstanceRequest) Reset() {
	*x = StartInstanceRequest{}
	mi := &file_cloud_provider_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartInstanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartInstanceRequest) ProtoMessage() {}

func (x *StartInstanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_provider_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartInstanceRequest.ProtoReflect.Descriptor instead.
func (*StartInstanceRequest) Descriptor() ([]byte, []int) {
	return file_cloud_provider_proto_rawDescGZIP(), []int{4}
}

type StartInstanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartInstanceResponse) Reset() {
	*x = StartInstanceResponse{}
	mi := &file_cloud_provider_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartInstanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartInstanceResponse) ProtoMessage() {}

func (x *StartInstanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_provider_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartInstanceResponse.ProtoReflect.Descriptor instead.
func (*StartInstanceResponse) Descriptor() ([]byte, []int) {
	return file_cloud_provider_proto_rawDescGZIP(), []int{5}
}

func (x *StartInstanceResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StartInstanceResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type GetProviderNameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProviderNameRequest) Reset() {
	*x = GetProviderNameRequest{}
	mi := &file_cloud_provider_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProviderNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProviderNameRequest) ProtoMessage() {}

func (x *GetProviderNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_provider_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProviderNameRequest.ProtoReflect.Descriptor instead.
func (*GetProviderNameRequest) Descriptor() ([]byte, []int) {
	return file_cloud_provider_proto_rawDescGZIP(), []int{6}
}

type GetProviderNameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProviderName  string                 `protobuf:"bytes,1,opt,name=provider_name,json=providerName,proto3" json:"provider_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProviderNameResponse) Reset() {
	*x = GetProviderNameResponse{}
	mi := &file_cloud_provider_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProviderNameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProviderNameResponse) ProtoMessage() {}

func (x *GetProviderNameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_provider_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProviderNameResponse.ProtoReflect.Descriptor instead.
func (*GetProviderNameResponse) Descriptor() ([]byte, []int) {
	return file_cloud_provider_proto_rawDescGZIP(), []int{7}
}

func (x *GetProviderNameResponse) GetProviderName() string {
	if x != nil {
		return x.ProviderName
	}
	return ""
}

type GetProviderVersionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProviderVersionRequest) Reset() {
	*x = GetProviderVersionRequest{}
	mi := &file_cloud_provider_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProviderVersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProviderVersionRequest) ProtoMessage() {}

func (x *GetProviderVersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_provider_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProviderVersionRequest.ProtoReflect.Descriptor instead.
func (*GetProviderVersionRequest) Descriptor() ([]byte, []int) {
	return file_cloud_provider_proto_rawDescGZIP(), []int{8}
}

type GetProviderVersionResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProviderVersion string                 `protobuf:"bytes,1,opt,name=provider_version,json=providerVersion,proto3" json:"provider_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetProviderVersionResponse) Reset() {
	*x = GetProviderVersionResponse{}
	mi := &file_cloud_provider_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProviderVersionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProviderVersionResponse) ProtoMessage() {}

func (x *GetProviderVersionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_provider_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProviderVersionResponse.ProtoReflect.Descriptor instead.
func (*GetProviderVersionResponse) Descriptor() ([]byte, []int) {
	return file_cloud_provider_proto_rawDescGZIP(), []int{9}
}

func (x *GetProviderVersionResponse) GetProviderVersion() string {
	if x != nil {
		return x.ProviderVersion
	}
	return ""
}

var File_cloud_provider_proto protoreflect.FileDescriptor

const file_cloud_provider_proto_rawDesc = "" +
	"\n" +
	"\x14cloud_provider.proto\x12\x06plugin\x1a\x1fgoogle/protobuf/timestamp.proto\"\x18\n" +
	"\x16GetInstanceInfoRequest\"\xd0\x01\n" +
	"\x17GetInstanceInfoResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x16\n" +
	"\x06region\x18\x04 \x01(\tR\x06region\x12\x12\n" +
	"\x04zone\x18\x05 \x01(\tR\x04zone\x12\x14\n" +
	"\x05state\x18\x06 \x01(\tR\x05state\x12;\n" +
	"\vlaunch_time\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"launchTime\"\x15\n" +
	"\x13StopInstanceRequest\"U\n" +
	"\x14StopInstanceResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"\x16\n" +
	"\x14StartInstanceRequest\"V\n" +
	"\x15StartInstanceResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"\x18\n" +
	"\x16GetProviderNameRequest\">\n" +
	"\x17GetProviderNameResponse\x12#\n" +
	"\rprovider_name\x18\x01 \x01(\tR\fproviderName\"\x1b\n" +
	"\x19GetProviderVersionRequest\"G\n" +
	"\x1aGetProviderVersionResponse\x12)\n" +
	"\x10provider_version\x18\x01 \x01(\tR\x0fproviderVersion2\xad\x03\n" +
	"\rCloudProvider\x12R\n" +
	"\x0fGetInstanceInfo\x12\x1e.plugin.GetInstanceInfoRequest\x1a\x1f.plugin.GetInstanceInfoResponse\x12I\n" +
	"\fStopInstance\x12\x1b.plugin.StopInstanceRequest\x1a\x1c.plugin.StopInstanceResponse\x12L\n" +
	"\rStartInstance\x12\x1c.plugin.StartInstanceRequest\x1a\x1d.plugin.StartInstanceResponse\x12R\n" +
	"\x0fGetProviderName\x12\x1e.plugin.GetProviderNameRequest\x1a\x1f.plugin.GetProviderNameResponse\x12[\n" +
	"\x12GetProviderVersion\x12!.plugin.GetProviderVersionRequest\x1a\".plugin.GetProviderVersionResponseB+Z)github.com/scttfrdmn/snoozebot/pkg/pluginb\x06proto3"

var (
	file_cloud_provider_proto_rawDescOnce sync.Once
	file_cloud_provider_proto_rawDescData []byte
)

func file_cloud_provider_proto_rawDescGZIP() []byte {
	file_cloud_provider_proto_rawDescOnce.Do(func() {
		file_cloud_provider_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cloud_provider_proto_rawDesc), len(file_cloud_provider_proto_rawDesc)))
	})
	return file_cloud_provider_proto_rawDescData
}

var file_cloud_provider_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_cloud_provider_proto_goTypes = []any{
	(*GetInstanceInfoRequest)(nil),     // 0: plugin.GetInstanceInfoRequest
	(*GetInstanceInfoResponse)(nil),    // 1: plugin.GetInstanceInfoResponse
	(*StopInstanceRequest)(nil),        // 2: plugin.StopInstanceRequest
	(*StopInstanceResponse)(nil),       // 3: plugin.StopInstanceResponse
	(*StartInstanceRequest)(nil),       // 4: plugin.StartInstanceRequest
	(*StartInstanceResponse)(nil),      // 5: plugin.StartInstanceResponse
	(*GetProviderNameRequest)(nil),     // 6: plugin.GetProviderNameRequest
	(*GetProviderNameResponse)(nil),    // 7: plugin.GetProviderNameResponse
	(*GetProviderVersionRequest)(nil),  // 8: plugin.GetProviderVersionRequest
	(*GetProviderVersionResponse)(nil), // 9: plugin.GetProviderVersionResponse
	(*timestamppb.Timestamp)(nil),      // 10: google.protobuf.Timestamp
}
var file_cloud_provider_proto_depIdxs = []int32{
	10, // 0: plugin.GetInstanceInfoResponse.launch_time:type_name -> google.protobuf.Timestamp
	0,  // 1: plugin.CloudProvider.GetInstanceInfo:input_type -> plugin.GetInstanceInfoRequest
	2,  // 2: plugin.CloudProvider.StopInstance:input_type -> plugin.StopInstanceRequest
	4,  // 3: plugin.CloudProvider.StartInstance:input_type -> plugin.StartInstanceRequest
	6,  // 4: plugin.CloudProvider.GetProviderName:input_type -> plugin.GetProviderNameRequest
	8,  // 5: plugin.CloudProvider.GetProviderVersion:input_type -> plugin.GetProviderVersionRequest
	1,  // 6: plugin.CloudProvider.GetInstanceInfo:output_type -> plugin.GetInstanceInfoResponse
	3,  // 7: plugin.CloudProvider.StopInstance:output_type -> plugin.StopInstanceResponse
	5,  // 8: plugin.CloudProvider.StartInstance:output_type -> plugin.StartInstanceResponse
	7,  // 9: plugin.CloudProvider.GetProviderName:output_type -> plugin.GetProviderNameResponse
	9,  // 10: plugin.CloudProvider.GetProviderVersion:output_type -> plugin.GetProviderVersionResponse
	6,  // [6:11] is the sub-list for method output_type
	1,  // [1:6] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_cloud_provider_proto_init() }
func file_cloud_provider_proto_init() {
	if File_cloud_provider_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cloud_provider_proto_rawDesc), len(file_cloud_provider_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cloud_provider_proto_goTypes,
		DependencyIndexes: file_cloud_provider_proto_depIdxs,
		MessageInfos:      file_cloud_provider_proto_msgTypes,
	}.Build()
	File_cloud_provider_proto = out.File
	file_cloud_provider_proto_goTypes = nil
	file_cloud_provider_proto_depIdxs = nil
}
